Correct ProxyHostPort name
gravitational/teleconsole pull request #8
Opened 2016-11-11 07:41 UTC by DoomHammer

This prevents build break as reported: https://aur.archlinux.org/packages/teleconsole/

2016-11-11 10:01 UTC, MikeMcQuaid requested changes

2016-11-11 10:01 UTC, MikeMcQuaid commented on clt/clt.go
> +		ProxyHostPort:          session.ProxyHostPort,
@DoomHammer Probably want to fix the indentation here.

2016-12-15 02:34 UTC, merged

2016-12-15 02:34 UTC, kontsevoy commented
Thanks @DoomHammer

2016-12-15 09:29 UTC, DoomHammer commented
Pleasure to be of any help :)